name: Bump scaffold

on:
  workflow_dispatch: {}

jobs:
  call-workflow:
    secrets: inherit
    uses: compulim/workflows/.github/workflows/bump-scaffold.yml@main
    with:
      package-name: $package-name
      use-react: true
