name: Bump dependencies

on:
  workflow_dispatch: {}

jobs:
  call-workflow:
    secrets: inherit
    uses: compulim/workflows/.github/workflows/bump-dependencies.yml@main
    with:
      package-name: react-chain-of-responsibility
