name: Bump scaffold

on:
  workflow_dispatch:
    inputs:
      package-name:
        default: react-chain-of-responsibility
        description: Name of the package
        required: true
        type: string
      use-react:
        default: true
        description: Use React
        required: true
        type: boolean

jobs:
  call-workflow:
    secrets: inherit
    uses: compulim/workflows/.github/workflows/bump-scaffold.yml@main
    with:
      package-name: react-chain-of-responsibility
      use-react: true
