name: Pull request validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  call-workflow:
    permissions: {}
    strategy:
      matrix:
        switch: [current, react-16, react-17, react-18]
    uses: compulim/workflows/.github/workflows/pull-request-validation.yml@main
    with:
      package-name: react-chain-of-responsibility
      skip-integration-test: false
      switch: ${{ matrix.switch }}
